### ISSUE TITLE
OpenAPI-Specification.yml missing DistributorsList

### ISSUE THREAD

**Issue by wincentek** [Sambruk/Open-Meal#17]
I think something went a bit wrong... Isn't /distributors supposed to return a list of distributors? But DistributorsListResponse has been completely removed.

**Comment by Lonestarrk** [comment]
https://github.com/Sambruk/Open-Meal/pull/18

**Comment by ricsv** [comment]
PR merged, please check so everything looks fine again @wincentek. Thanks for fixing this issue quickly @Lonestarrk !
