### ISSUE TITLE
The examples are not equal to the specification

### ISSUE THREAD

**Issue by Lonestarrk** [Sambruk/Open-Meal#22]
The examples are different from the specification... why have examples when it only clutters the specs and drifts if not updated

![image](https://user-images.githubusercontent.com/9883183/174015592-9a5b70ab-9635-4ea0-8f11-fd43020b5065.png)

**Comment by ricsv** [comment]
Examples are a valuable addition to developers because it gives a better idea of what data is actually produced by the API. But the examples have to be correct. How far from correct is the example above?

**Comment by Lonestarrk** [comment]
https://github.com/Sambruk/Open-Meal/pull/23

**Comment by ricsv** [comment]
Thanks @Lonestarrk
