### ISSUE TITLE
3.2 - meals endpoint should also return 404 with ProblemDetails

### ISSUE THREAD

**Issue by wincentek** [Sambruk/Open-Meal#7]
The meals endpoint can also use the distributirId to lookup more details on a distributor. Hence, the 404/ProblemDetails should also be one of the return types.

This will probably also be used once the meals/{mealId} endpoint exist.

**Comment by wincentek** [comment]
Copied from chat of PR#6

[Lonestarrk](https://github.com/Lonestarrk) commented [12 hours ago](https://github.com/Sambruk/Open-Meal/pull/6#issuecomment-1108912802)

I disagree because an empty list is a valid reponse.. 404 NOT FOUND should be used only when a specific resource requested via resource/{resourceId} is missing and should only happen if an invalid id is provided or the resource is deleted.

**Comment by wincentek** [comment]
You do request a resource, the distributor, by id.
If the distributorId, which is required to be used when supplied, is not found using the distributorId a 404 should be returned.

The empty list is a result of the distributor not providing any meals, not that the distributor doesn't exist at all.

**Comment by wincentek** [comment]
I've reconsidered. The 404 should apply to the future endpoint distributors/{distributorId}/meals.

But I do think an error response would be appropriate. As a consumer I really would need to know why the list of expected meals are empty when the distributor claims they've provided the meals into the system.

Still; There's the difference between no registered meals and non-existent distributor.

**Comment by Lonestarrk** [comment]
on distributors/{distributorId}/meals 404 makes sense because the endpoint suggests you are retrieving first a specific distributor and then a subset meals...

but /meals?distributorId={distributorId} is only a filter and should remain such.. 
if a distributor is subsequently deleted this should not cause errors (404) in a consumer UI application only case an empty result.. its easier for an API consumer to use the API with less special cases.

404 suggests that the user has made a mistake or accessed something that does't exist. i.e the Endpoint doesn't exist like with distributors/{distributorId} where the id is part of the endpoint

https://stackoverflow.com/questions/6045895/should-a-restful-api-return-404-for-arrays-of-objects

**Comment by wincentek** [comment]
I think we have different approaches. My approach is not from the _end user_ (UI) point of view. An empty array is perfectly fine to present in the _UI_.

My perspective is from the developer of the app/service that consumes the API (again, not the actual end user in the UI). As the data provider and the data consumer will far from always be the same company, how will the consumer implementation be able to know and log/handle that a faulty distributorId has been provided?

I do mean an error response of some sorts, it doesn't have to be 404 (suggestion is 400/Bad Request).

**Comment by Lonestarrk** [comment]
Any error code above 399 suggests application error 

I ment for constancy in api behaviour for the consumer (UI coder) independent if an array is empty or not should have same respons code 200 

This stackoverflow post summarise it good.

https://stackoverflow.com/questions/13366730/proper-rest-response-for-empty-table

**Comment by wincentek** [comment]
Hmmm, ok.
Let's stick to returning an empty list reqardless of the distributorId-filter **IF** we also add the endpoint /distributors/{distributorId}/meals.

That's the only way for the consumer implementation to know that an empty list is actually on purpose. Using only the /meals with filter distributorId means that EVERY time an empty list is returned, there might be an issue with a non existent distributor resource.

What I'm trying to say is that /meals with no special treatment of invalid distributorId requires a "proper" endpoint that provides that behaviour.

Is that a good compromise?

**Comment by Lonestarrk** [comment]
I have reconsidered that 400 bad request might be good as it would inform
the end user that the URL used is no longer valid and let them know to find
a new and valid distributor

Den tors 28 apr. 2022 09:43Wincent Ek ***@***.***> skrev:
